### ISSUE TITLE
Include remote IP address in default output

### ISSUE THREAD

**Issue by troy** [roidrage/lograge#10]
This would make lograge usable as a drop-in replacement for many more apps.

If the remote IP isn't available elsewhere, it may entail redefining/monkeypatching [ActionController::Instrumentation](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/instrumentation.rb#L18) so the remote IP is provided to log subscribers. Something like:

```
ActionController::Instrumentation.send(:define_method, "process_action") do |arg|
  raw_payload = {
    # .. the existing keys ..
    :ip         => request.remote_ip
  }

  # define the ActiveSupport::Notifications events
end
```

If you would accept a patch to add this (or can suggest a better way to obtain the remote IP), let me know and I'll give it a whirl.

**Comment by pomartel** [comment]
I also had to do a lot of digging and finally found the ip address here:
``
event.payload[:headers][:REMOTE_ADDR]
``

**Comment by qbantek** [comment]
`event.payload[:request].remote_ip` seems to be providing the expected results for lograge 0.11.2
