### ISSUE TITLE
Seperate  log for JSON format

### ISSUE THREAD

**Issue by jenorish** [roidrage/lograge#100]
I want JSON format log in seperate file, so In config application.rb

`config.lograge.logger = ActiveSupport::BufferedLogger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"`

But still JSON format log is coming in production.log only.

Could you please correct me

Thanks for any help

**Comment by jenorish** [comment]
I have installed with
gem `lograge`

But it has installed `lograge (0.3.0)`

In `lograge-0.3.0` in this tag below code is not there,But in master this code is there.

`Lograge.logger = app.config.lograge.logger`

Could you please merge the code to this tag?

 https://github.com/roidrage/lograge/blob/master/lib/lograge.rb#L126

**Comment by pxlpnk** [comment]
Hey, afaik @benlovell is working on cutting a release. I think if you can wait a bit more it should be in there.
In the meanwhile you could (I hate myself already for advising this) point your Gemfile to the current master to obtain the code.

**Comment by jenorish** [comment]
Ok Thanks.

**Comment by benlovell** [comment]
We'll have a release cut this weekend for sure. :+1:
