### ISSUE TITLE
Display with DB query

### ISSUE THREAD

**Issue by vtrkanna** [roidrage/lograge#102]
HI

How display with DB query on that logger

method=GET path=/article/24694 format=html controller=article action=show status=200 duration=7899.91 view=3193.04 db=1376.15

I want to display DB query, it's possible

**Comment by bbhoss** [comment]
According to the README it looks like this is something they expect you to track with NewRelic.

**Comment by pxlpnk** [comment]
Depending on how your controller looks like there might be many queries involved. 
I don't think lograge is the right tool to track this information, as @bbhoss already mentioned would make  a tool like NewRelic more sense here.
