### ISSUE TITLE
Cannot load Formatter in development.rb

### ISSUE THREAD

**Issue by matteomelani** [roidrage/lograge#119]
in development.rb I have added:
```ruby
config.lograge.enabled = true
config.lograge.formatter = Lograge::Formatters::Json.new
```
and when I start the server I get:

```ruby
config/environments/development.rb:37:in `block in <top (required)>': uninitialized constant Lograge::Formatters (NameError)
```
Any idea?

I do have the gem 'lograge' in the Gemfile and if I remove the config.lograge.formatter = Lograge::Formatters::Json.new everything works just fine.

**Comment by pxlpnk** [comment]
Is the lograge gem in a group in your Gemfile?

**Comment by matteomelani** [comment]
No, it is not. It is just in the Gemfile.

**Comment by matteomelani** [comment]
I uninstalled the gem and re-installed and now it is working fine.
