### ISSUE TITLE
`Could not log "process_action.action_controller" event. ArgumentError: wrong number of arguments (0 for 1)` when validation error occured

### ISSUE THREAD

**Issue by a-know** [roidrage/lograge#126]
#### Issue
In bug fix of the issue #110 , you had modified following this.

https://github.com/roidrage/lograge/pull/112/files#diff-d3a7c7717409a1c1353805f9579b980bR64

But, in `get_error_status_code` method, there is `exception_object = exception.constantize.new` .

https://github.com/roidrage/lograge/pull/112/files#diff-d3a7c7717409a1c1353805f9579b980bR71

If the exception requires arguments (for example, as of `ActiveRecord::RecordInvalid`), `exception_object = exception.constantize.new` throw `ArgumentError: wrong number of arguments`.
Such errors cause `Could not log "process_action.action_controller" event. ArgumentError: wrong number of arguments (0 for 1)` in 85 line of `activesupport-4.2.0/lib/active_support/log_subscriber.rb` .

#### Environments

* Lograge version : `0.3.2`
* Rails version : `4.2.0`
* RVM/rbenv/chruby/etc are not used
* Ruby version : `2.2.2p95 (2015-04-13 revision 50295)`
* OS : Cent 7

**Comment by sakuro** [comment]
Should use `ActionDispatch::ExceptionWrapper.status_code_for_exception` instead of instantiating a new exception from the class name and use its name?

**Comment by spscream** [comment]
Any workarounds? I have the same issue with logger.

**Comment by pxlpnk** [comment]
I will look into this the coming weekend. Thanks for the input @sakuro

**Comment by pxlpnk** [comment]
I looked into it, 
using `ActionDispatch::ExceptionWrapper.status_code_for_exception` would work for a number of errors:
https://github.com/rails/rails/blob/1ca13b47da46247345a0d4547edc495f0cc83bf6/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L10-L20

But it would completely ignore the `ActiveRecord::NotFound` and return a 500 for this.
Maybe there could be a combination of both approaches to catch more of the status codes.

**Comment by sakuro** [comment]
AR seems that it registers AR specific exceptions to the mappings, right?

https://github.com/rails/rails/blob/1ca13b47da46247345a0d4547edc495f0cc83bf6/activerecord/lib/active_record/railtie.rb#L25

**Comment by pxlpnk** [comment]
I expected that too after reading the code, but when executing the code with tests there is no AR specific mapping in the exception wrapper. Maybe this just gets loaded when you run rails as an _"actual"_ instance?

**Comment by andywenk** [comment]
I have the same issue in our production system. Can I help with any info? Any progress here? Thanks a lot!!!

**Comment by pxlpnk** [comment]
Sorry I am currently a bit down under. We are happy about a pull request that would fix this.

**Comment by benlovell** [comment]
I'm looking into this now. Hold tight.

**Comment by benlovell** [comment]
@pxlpnk Ideally we'd have at least a few integration specs that load rails in its entirety and to cover this end to end, but for now at least I think #134 should resolve this issue.
