### ISSUE TITLE
question: is it possible to show lograge info in `config.log_level = :warn` log level?

### ISSUE THREAD

**Issue by okliv** [roidrage/lograge#128]
i have setup (environments/production.rb)

    config.log_level = :warn

for my application

looks like lograge works like expected (for me) only in 

    config.log_level = :info

mode...

is this a bug or can i somehow force lograge to write its info when log captures only warns and errors?

for example, i have a warning

    WARNING: Can't verify CSRF token authenticity

but i can't see for which url it was fired

thank you

**Comment by ncancelliere** [comment]
It looks like it's hard coded to only work with :info  
```ruby
#lib/lograge.rb#85-87
 
 # Loglines are emitted with this log level
  mattr_accessor :log_level
  self.log_level = :info
```

**Comment by pratik60** [comment]
@okliv 

If you have config like below

#Log rotation
config.log_level = :warn
config.logstasher.suppress_app_log = false
config.logstasher.enabled = true

Does logstasher stay in info mode, but your normal logs stay in warn mode?

**Comment by okliv** [comment]
i believe i need to replace logstasher to lograge (i do not use logstasher gem in context of this question)...

Nonetheless, this snippet didn't help... i still do not see request parameters in my production log
