### ISSUE TITLE
Periodically showing "x number of requests" to controller#action?

### ISSUE THREAD

**Issue by hackeron** [roidrage/lograge#129]
I have a controller action called "snapshot" - this action is called 200 times per second fetching live snapshot from many cameras.

I would like to know that this controller is being called, but I don't want to log every request.

Either to log every say 100 requests to this action, or to periodically say x requests to this action. Is there any way to achieve this?

**Comment by benlovell** [comment]
The technique you are referring to is essentially _sampling_. This is theoretically possible with lograge but we don't support this behaviour out of the box. However, you could hack together an approach with `ignore_custom` and some kind of state to track the number of requests to the action:

```ruby
config.lograge.ignore_custom = lambda do |event|
  # track the state and return false until you hit your required sample rate here 
end
```
