### ISSUE TITLE
Logging runtime variables

### ISSUE THREAD

**Issue by maximski** [roidrage/lograge#133]
I would like to log runtime variables, to be concrete I want to log the current_user.id, where current_user is provided by Devise. Is this possible? Because the log will just tell me that variable is unknown.

**Comment by pxlpnk** [comment]
You can then add custom variables to the event to be used in `custom_options` (available via the `event.payload` hash)

```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    super
    payload[:current_user_id] = current_user.id
  end
end
```

This however will only work if the current_user actually exists

**Comment by maximski** [comment]
Oh that's perfect. I have overlooked that in the readme, I am sorry.
