### ISSUE TITLE
Log custom events (from rake tasks, models etc)

### ISSUE THREAD

**Issue by pratik60** [roidrage/lograge#136]
I started using the lograge gem for json logs which could easily be sent to logstasher, and its working great.

But if you wanted to log some custom events from controller or model, what can you do? For example -: the lines Rails.logger.warn("Custom data #{@custom_data.inspect}") no longer shows anything in the log, but the information is critical for debugging purposes. 

How can I add such things with the lograge gem?

**Comment by benlovell** [comment]
It doesn't make much sense to include verbose output in the lograge formatted log, however you can also keep your original rails log for this purpose:

```ruby
MyApp::Application.configure do
  config.lograge.keep_original_rails_log = true
end
```

**Comment by rabidscorpio** [comment]
I never understand why people effectively say "why are you doing that" when someone asks a question just because they don't understand the original poster's use case.  That wasn't his question, he wanted to know "How."  Saying that you should use the default rails logging is a nonstarter and completely defeats the purpose of using lograge!

@pratik60 Why not use "append_info_to_payload" in your application controller as is mentioned in the documentation?

**Comment by pratik60** [comment]
So, our requirement primarily stems from the need to find the critical path in our rake tasks. Our rake tasks spin threads for each company signed on our platforms, and we need to find how much time it took for each company. For those it took really long, we will investigate further, and see if we can optimise the code. 

I don't want to keep the Rails log, because it is far too verbose, and digging through it is a pain.

Also, we have set up ELK stack, and I really wanna try and use logstasher + kibana for this. 

task=fetch_analytics_data message={"company1": 330s, "company2": 660s ....} format=json ......

No way, we can tweak and pass such things to the log? 

Its not really a part of the params or anything, so don't know if append_info_to_payload is still the one to use.

**Comment by benlovell** [comment]
@rabidscorpio Of course I'm asking 'why are you doing that' - exactly so I can understand the use case.  You'll notice I didn't close this issue, so I was perfectly happy to field further questions. Thanks for jumping in and offering to help, regardless.

@pratik60 Thank you for clarifying your issue. Be mindful that lograge emits log messages at the `:info` level by default. So to buy-in to lograge you should either configure the log level or use Rails' `info` logger. You could then perhaps include this output from `append_info_to_payload` or pass the raw data along to your own customised formatter plugin. The API is fairly slim ([here's the built-in examples](https://github.com/roidrage/lograge/tree/master/lib/lograge/formatters)) so hopefully this shouldn't be too tricky. 

Give me a shout if you need further help.

**Comment by pratik60** [comment]
Will do thanks....

Also, isn't it normal practice to log things in exception? There is exception notifier for all events that you haven't caught, but those that you have, wouldn't you still want to log them further?

Will start looking at the examples, and see if makes sense. Thanks once again :-)

**Comment by benlovell** [comment]
@pratik60 while you certainly could log things at the `:error` level, the question then is how you make sense of the large and often pretty deep stack trace.

My personal preference is to handle errors with a dedicated notifier service (YMMV). But as I said, you could log at `:error` and potentially transform the stack trace into something in keeping with the principals of lograge.

**Comment by benlovell** [comment]
@pratik60 did you get the assistance you needed?

**Comment by pratik60** [comment]
@benlovell Well, did get a workaround. One of the major reasons for us to move to lograge was to use it in combination with this awesomeness called logstash & kibana...And I think I have only uncovered the basic layer of kibana - Like most frequently used action, most expensive actions etc

Have been using the rails logger for these custom tasks, but not integrated in with it yet. Give me a week more, and then I will close this issue, if I don't need any more help.

**Comment by pratik60** [comment]
Still not getting time for this :-(

Closing it for now.

**Comment by iGEL** [comment]
Hey guys, I've created a PR for this, please have a look: #144
