### ISSUE TITLE
Enabling lograge silences all logs

### ISSUE THREAD

**Issue by mordocai** [roidrage/lograge#137]
So this is more of a support request than anything else, but I didn't see an official IRC channel or anything to ask questions so this seemed to be the best place. I doubt this is actually a problem with lograge itself.

We are updating our production application (that unfortunately is proprietary so I can't just give access and ask for help) from rails 3.2 to rails 4.2. We have deployed a test instance of it and noticed that we were getting no logs to the log file. I was then able to reproduce this with the development environment. If we disable lograge, we get them back. Even just config.lograge = true with no other lograge config will cause our logs to disappear. When running the development environment and bundle exec rails s we don't get logs to STDOUT or the log file.

If it helps, we are having similar issues with newrelic(The traceback data is incorrect, showing that everything is spending all time in RouteSet which is obviously incorrect) and have a ticket open with them. 

I've searched around the Internet extensively looking for other people having a similar issue and can't find anything, so any debugging advice you can give would be greatly appreciated. I'm at a loss. My only guess is that something has gone wrong with the rails Events/Callbacks system but I know very little about it myself so am not sure what could have gone wrong there.

Thanks in advance.

**Comment by benlovell** [comment]
Hey @mordocai - sorry to hear. If you could produce us with a small and focused repro that would certainly help. Otherwise can you post your lockfile and your associated lograge/rails logging configuration?

**Comment by mordocai** [comment]
I haven't been able to reproduce this with small and focused repros unfortunately. I'll post that information up shortly.

**Comment by mordocai** [comment]
Gemfile.lock: https://www.refheap.com/dd7ed54ccd88760f67181a675
Lograge config: https://www.refheap.com/ab9ae3cb59cb094b6be8c573b

It is important to note that I can reproduce the issue when everything but config.lograge.enabled = true commented out of that config. I cannot reproduce the issue when I set config.lograge.enabled = false.

**Comment by pxlpnk** [comment]
Right from your files I can not see why it would not work. Can you maybe inspect the rails logger and try to figure out what it has set as destination?
There could also be a a monkeypatch somewhere in the system. Lograge itself does not change where the log goes.

**Comment by mordocai** [comment]
Sooooo.... uh... this is embarrassing. We had a monkey patch doing this: 

````
module ActiveSupport
  module Notifications
    class Instrumenter

      # Inspiration came from this Gist: https://gist.github.com/bf4/5911868
      # The original rails code can be found here:
      #   https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/notifications/instrumenter.rb
      def instrument(name, payload={})
        started = Time.now

        begin
          yield
        rescue Exception => e
          payload[:exception] = [e.class.name, e.message]

          # Add the stacktrace to the event notication so we can log it
          payload[:stacktrace] = e.backtrace

          raise e
        ensure
          @notifier.publish(name, started, Time.now, @id, payload)
        end
      end
    end
  end
end
````

In our initializers. I missed it the first time, but looked at again due to your comment about it being a monkey patch.

So thanks, we fail! Sorry to waste time. Hopefully helps some future googlers at least.

**Comment by pxlpnk** [comment]
No worries, happy we could help and you fixed the problem. :dancer:

**Comment by benlovell** [comment]
:+1:
