### ISSUE TITLE
"cache: ... miss" not removed from logs

### ISSUE THREAD

**Issue by jackrg** [roidrage/lograge#140]
I added the lograge gem, restarted my web servers and got the expected results, except that the "cache: ... miss" lines were still present. I found that in order to remove the cache lines I had to add the following line to "environment/production.rb": 
`config.action_dispatch.rack_cache = {:metastore => "rails:/", :entitystore => "rails:/", :verbose => false}`
contrary to what the "read.me" doc says. Is this a bug, a documentation issue, or something else?

**Comment by pxlpnk** [comment]
What rails version are you using? How does your lograge config look like? Can you provide some source code to reproduce the issue?

**Comment by roidrage** [comment]
This is indeed coming from rack-cache: https://github.com/rtomayko/rack-cache/blob/master/lib/rack/cache/context.rb#L80-L82

I've noticed this early on building lograge, and the easiest fix is indeed to set the `verbose: false` option for rack-cache, but lograge could also override `rack.logger`: https://github.com/rtomayko/rack-cache/blob/master/lib/rack/cache/context.rb#L291-L297

Sorry if I'm barging in, just wanted to add a bit of context from previous experiences with this.

**Comment by benlovell** [comment]
>Sorry if I'm barging in

Never, and by the way - HAPPY BIRTHDAY @roidrage :cake: :balloon: :gift: :heart:

**Comment by pxlpnk** [comment]
Happy birthday @roidrage. Also please always give your input when you have some! :green_heart:

**Comment by jackrg** [comment]
Sorry for not giving more context: Rails 3.1.3, Ruby 1.9.3, LogRage 0.3.4

From environments/production.rb:

…
  # Add thread id to Log
  config.log_tags = [ Proc.new { Thread.current.object_id }]
  
  # Enable LogRage Log Re-formatting
  config.lograge.enabled = true
  config.lograge.custom_options = lambda do |event|
    params = event.payload[:params].reject do |k|
      ['controller', 'action'].include? k
    end
    { "params" => params }
  end
  
  # Remove "cache: '/' miss" messages from the log
  config.action_dispatch.rack_cache = {:metastore => "rails:/", :entitystore => "rails:/", :verbose => false}
...
