### ISSUE TITLE
Adding custom header to the logs

### ISSUE THREAD

**Issue by gingermusketeer** [roidrage/lograge#141]
What is the best way to go about adding a custom header to the request logs?

I have a header `X-Consumer` which allows me to easily see which consumer is making a request. It would be great to see this in the logs

Versions
- Rails: 4.2.3
- Lograge: 0.3.4

**Comment by benlovell** [comment]
Have you checked the docs, specifically how implementing `append_info_to_payload` in your `ApplicationController` and `config.lograge.custom_options` interplay to satisfy adding custom data? Take a look there and be sure to ask any specific questions should you get stuck.

**Comment by gingermusketeer** [comment]
@benlovell Thanks. For some reason i missed that. 

Ended up adding a lambda to the app's log_tags so that every log is tagged with the header

**Comment by benlovell** [comment]
No problem. :heart:
