### ISSUE TITLE
how to handle backtrace?

### ISSUE THREAD

**Issue by epinault** [roidrage/lograge#142]
So I am using lograge and the Logstash output format. What I see is the correct json messages in my log files.. but the backtrace is still following in the log. That means logstash receive those line as non json  and create json_failure when trying to parse those line. So the issue is the intermingling between json line and non json one. 

Is there any best practices I can follow? what would you recommend?

**Comment by pxlpnk** [comment]
Hey, in general using an error/exception tracker to record those kinds of events is the best practice here.

What are you planning to to with the stack trace?

**Comment by epinault** [comment]
What do you mean by tracker? What I am trying to do is have all the normal traffic line in the log to be printed in Logstash Event format so logstash can parse it and use it in elasticsearch to report. But  what I noticed for errors such as backtrace it just print the backtrace as normal line. unfortunately Logstash see them and try to parse them and fails since they are not json format.

I can easily filter them out of the log using a query filter but was curious of best practices. Is it possible to turn the backtrace off? or send them some other way? Backtrace would only be useful for debuggin but nothing else at this point

**Comment by dnd** [comment]
I'm with @epinault. I ship my logs to logstash, and even though I also use Airbrake, having the exception that occurred during a request as well as the stacktrace right in my parsed error logs makes diagnosing problems a lot easier.

I would also argue that that exception is part of the request that occurred. It's not its own standalone entity

**Comment by benlovell** [comment]
I've been thinking about some solutions to this recently and I'm hoping to have something to play with shortly.

**Comment by dnd** [comment]
I look forward to seeing what you come up with. Does this maybe tie in as well with #27?

**Comment by epinault** [comment]
What I came up is adding a filter in the logstash to ignore non json message  for now

filter {
  if [type] == "feeder" 
  {
    if [message] =~ /^\{/
    {
      json {
        source =>"message"
	add_field => { "category" => "rails_request"}
	
      }
    }
  }
}

**Comment by igstan** [comment]
Hi, folks! Is there update on this issue? We currently have our backtrace lines interleaved with normal request lines in Kibana and it's not helpful at all.
