### ISSUE TITLE
How to write to separate log files based on some condition?

### ISSUE THREAD

**Issue by sharang-webonise** [roidrage/lograge#143]
I spent a lot of time looking at the source to see how this can be plugged in but I'm wondering if anyone has already done this before. Basically I need to write to different logs for API and web-application requests. The differentiation can be done based on the path of the request. Is there any built-in functionality that can do this as of now?

**Comment by pxlpnk** [comment]
This is currently not part of lograge. Lograge just takes care about the formatting and not where the logs go. For this you could create your own customized instance of a logger that dispatches the messages to different loggers based on your criteria.
