### ISSUE TITLE
Lograge and ActionController::Metal

### ISSUE THREAD

**Issue by erlandsona** [roidrage/lograge#147]
Lograge v 0.3.4
Rails v 4.2.4
RVM v 1.26.11 
Ruby v 2.2.2p95
OSX v 10.10.5
A stacktrace or log output if available...
```bash
$ rails s
=> Booting Puma
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
  ActiveRecord::SchemaMigration Load (0.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  Client Load (1.4ms)  SELECT  "clients".* FROM "clients" WHERE "clients"."auth_token" = $1  ORDER BY "clients"."name" ASC LIMIT 1  [["auth_token", "secret_password_that_no_one_knows"]]
   (1.4ms)  SELECT COUNT(*) FROM "models"
  Model Load (2.0ms)  SELECT  "models".* FROM "models"  ORDER BY "models"."name" ASC LIMIT 100 OFFSET 0
```
I'm using an ActionController::Metal setup and I'm trying to familiarize myself with the modules included in ActionController::Base to compare against but I'm just not quite there yet...

Lograge works great if I'm using ActionController::Base... I can change the formatting all day long and it's as easy as the README.md states. But when I switch to inheriting from ActionController::Metal I loose the Completed 200 OK in 84ms (Views: 2.7ms | ActiveRecord: 17.2ms). And then also even with ActionController::Base that's the only line that's getting formatted...

Does lograge format the ActiveRecord part of the logs too??? I'm just looking for a simple easier to read Logging mechanism for a bare bones rails-api.

```
Started GET "/models?per_page=100" for ::1 at 2015-10-23 23:09:03 -0500
  ActiveRecord::SchemaMigration Load (0.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by API::V1::ModelsController#index as JSON
  Parameters: {"per_page"=>"100", "model"=>{}}
  Client Load (1.4ms)  SELECT  "clients".* FROM "clients" WHERE "clients"."auth_token" = $1  ORDER BY "clients"."name" ASC LIMIT 1  [["auth_token", "secret_password_token"]]
   (2.3ms)  SELECT COUNT(*) FROM "models"
  Model Load (2.1ms)  SELECT  "models".* FROM "models"  ORDER BY "models"."name" ASC LIMIT 100 OFFSET 0
```

**Comment by benlovell** [comment]
Include `ActionController::Instrumentation` in your metal controller and that should get things working there. With regards Active Record, that's not something we support just now. But I do have some plans for the near future...

**Comment by erlandsona** [comment]
Can't wait! Thanks for the tip! you can close this if you want!

**Comment by benlovell** [comment]
❤️💚💛
