### ISSUE TITLE
How do I add a time stamp?

### ISSUE THREAD

**Issue by matteomelani** [roidrage/lograge#15]
I am not sure i get this line "use a proper log formatter instead."

thanks!

**Comment by patrickdavey** [comment]
I didn't like the time format the event gave me in https://github.com/roidrage/lograge/issues/15#issuecomment-9530995 . Just using the Time class worked neatly for me.

```ruby
MyApp::Application.configure do
  config.lograge.enabled = true

  # add time to lograge
  config.lograge.custom_options = lambda do |event|
    {
       time: Time.now.utc
    }
  end
end
```
