### ISSUE TITLE
unpermitted_parameters logging?

### ISSUE THREAD

**Issue by aripollak** [roidrage/lograge#152]
When `config.action_controller.action_on_unpermitted_parameters = :log` is set, Rails 4 can emit an "unpermitted_parameters.action_controller" event, which is normally handled by the default LogSubscriber, but lograge uses its own subscriber so the unpermitted parameters never got logged. Would it make sense for lograge to handle that event and add it to the log line automatically if it's set? By default the `action_on_unpermitted_parameters` config is unset so it would never show up in the log, but if you've explicitly set that config, it would.

**Comment by pxlpnk** [comment]
I like this idea.
A PR is very welcome. :dancers: so we have a base for discussion.

The default behaviour should be off I think. And people can enable it when they need it.
