### ISSUE TITLE
Graylog2 Formatter Prefixes

### ISSUE THREAD

**Issue by pex** [roidrage/lograge#153]
In [`Formatters::Graylog2`](https://github.com/roidrage/lograge/blob/v0.3.4/lib/lograge/formatters/graylog2.rb#L14) you are prefixing all keys with an underscore except `short_message`. After reading [GELF Docs](https://www.graylog.org/resources/gelf/) this seems wrong to me. One might want to pass `host` via `custom_options` to the corresponding log entry. Should we add a list of unescaped keys? Or is there another best practice when using lograge and Graylog2 without [GELF gem](https://rubygems.org/gems/gelf) (and e.g. [heroku log drains](https://devcenter.heroku.com/articles/log-drains) instead).

This might be an issue for @lennartkoopmann as well.

**Comment by pxlpnk** [comment]
What would be the expected outcome? I am not very familiar with GELF.
From what I understood from the docs the current implementation seems correct to me. 
Can you maybe provide an example on how it looks right now and what you think it should look like?

**Comment by pex** [comment]
We've been using lograge with GELF formatter, logging to STDOUT (in order to send logs via heroku log-drains to Graylog). This results not only in strange prefixes but plain ruby hashes being logged. For me this looked like a bug.

After thinking about this I assume @lennartkoopmann expected people to use their custom logger [GELF Gem](https://rubygems.org/gems/gelf) to log via UDP.

Actually I think this is worth documenting when speaking about Graylog/GELF support for lograge. The current implementation is not (only) about GELF as a format but requires a special logger (e.g. [GELF Gem](https://rubygems.org/gems/gelf) in order to understand ruby hashes outputted by the GELF formatter.

**Comment by pxlpnk** [comment]
Thank you for the detailed response. Would you be so kind to create a pull request that adds this documentation to the readme? 
Maybe @lennartkoopmann could clarify your findings before, so that we are sure we are on the right track.

**Comment by benlovell** [comment]
Any interest in this before I close for inactivity?

**Comment by pex** [comment]
I'm out. Thanks, though!
