### ISSUE TITLE
How to log request and response body?

### ISSUE THREAD

**Issue by joshuamcginnis** [roidrage/lograge#156]
I've got a very simple implementation, but I can't seem to figure out how to log the request and response body.

In: /config/initializers/lograge.rb`
```ruby
MyApp::Application.configure do
  config.lograge.enabled = true
  config.lograge.formatter = Lograge::Formatters::Json.new
end
```
Example Log:
```json
{"method":"GET","path":"/support_users/sign_in","format":"html","controller":"support/sessions","action":"new","status":200,"duration":137.41,"view":101.48,"db":6.05 }
```
Is there a quick way to add the request and response body (among others) to the logs?

**Comment by pxlpnk** [comment]
You can add them using:
```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    super
    payload[:request_data] = request.whatever_data_is_in_here
  end
end
```
This is documented in the readme. https://github.com/roidrage/lograge#installation
However I do not recommend you to dump request body into the logs as it will become too messy.

**Comment by joshuamcginnis** [comment]
I tried this per the documentation, but it still doesn't work.

For example, here's what I've got:
```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    super
    payload[:foo] = bar
    p payload
  end
end
```

This outputs:
```ruby
// payload contents (foo is present)
{:controller=>"Support::SessionsController", :action=>"new", :params=>{"controller"=>"support/sessions", "action"=>"new"}, :format=>:html, :method=>"GET", :path=>"/support_users/sign_in", :status=>200, :view_runtime=>10.425124084576964, :db_runtime=>3.7260000000000004, :foo=>"bar"}
// actual log sent to fluentd (foo is not present)
{"method":"GET","path":"/support_users/sign_in","format":"html","controller":"support/sessions","action":"new","status":200,"duration":22.64,"view":10.43,"db":3.73}
```

Is there another step I need to take to ensure these additional payload values are logged?

**Comment by pxlpnk** [comment]
I have never used fluentd, but from what I can see in the log it alters the log information quite a bit. My wild guess it that fluentd is maybe stripping it out (?)

**Comment by joshuamcginnis** [comment]
Yea, we can close this. It's a fluentd config that I need to adjust. Future readers, head over to the fluentd gem for more info: https://github.com/actindi/act-fluent-logger-rails

**Comment by pxlpnk** [comment]
Thank you for sharing the piece of information. :smiley:
