### ISSUE TITLE
Help Setting Up Lograge

### ISSUE THREAD

**Issue by nwalke** [roidrage/lograge#159]
We have logging set up like so:
```
  config.log_level = :info
  config.log_tags = [:uuid]
  require 'syslogger'
  logger = Syslogger.new("Rails", Syslog::LOG_PID, Syslog::LOG_LOCAL7)
  config.lograge.enabled = true
  config.lograge.formatter = Lograge::Formatters::Json.new
  config.logger = ActiveSupport::TaggedLogging.new(logger)
  config.logger.level = ActiveSupport::Logger.const_get(config.log_level.to_s.upcase)
```

We however continue to get the "rendered" log messages as shown in the README.  I'm very unfamiliar with Rails logging and how this should work properly.  I'd like to not have the "rendered" log messages any more, no one here uses them.  I also need it to go to logging facility 7 so that logs get shipped out to Loggly.  This currently works, but like I said, has all the "rendered" messages.

Any help you can provide or documentation hints would be greatly appreciated.

**Comment by pxlpnk** [comment]
@nwalke what environment are you testing in? What environment did you set up the config for?

**Comment by nwalke** [comment]
We were testing under "staging".

**Comment by pxlpnk** [comment]
@nwalke so all the above code is stored within your staging.rb environment file?
It seems weird that you are seeing the rendered messages. What version of rails are you using?

**Comment by pxlpnk** [comment]
@nwalke did you resolve the issue? What was the cause?

**Comment by adamgeorgeson** [comment]
Also interested in the cause as have seen this too.

**Comment by nwalke** [comment]
Unfortunately I don't remember how or if this was ever resolved.  I've moved on from the company that was using this.

**Comment by adamgeorgeson** [comment]
No worries @nwalke, cheers for getting back to me! I'll do some digging then maybe raise a new issue.

**Comment by adamgeorgeson** [comment]
I think I have found the issue for me. New app I've taken on and there was already some historical commented out usage in `production.rb`.

**Comment by voducvu** [comment]
I have faced the same issue. And I found the root cause. Some gems overrides the ActionView::LogSubscriber (eg. Kaminari gem). It would cause the lograge's unsubscribe method fail. Calling public_method(false) on the ActionView subscriber return s unexpected methods list (doesn't include the ActionView::LogSubscriber event handlers)
https://github.com/roidrage/lograge/blob/master/lib/lograge.rb
`  def unsubscribe(component, subscriber)
    events = subscriber.public_methods(false).reject { |method| method.to_s == 'call' } # this line cause the bug
    events.each do |event|
      ActiveSupport::Notifications.notifier.listeners_for("#{event}.#{component}").each do |listener|
        if listener.instance_variable_get('@delegate') == subscriber
          ActiveSupport::Notifications.unsubscribe listener
        end
      end
    end
  end`
Hope this would help someone still struggle
