### ISSUE TITLE
Question on RequestLogSubscriber

### ISSUE THREAD

**Issue by zhuochun** [roidrage/lograge#172]
In RequestLogSubscriber, The `controller` and `action` are read from `payload[:params]`:

``` ruby
    def initial_data(payload)
      {
        method: payload[:method],
        path: extract_path(payload),
        format: extract_format(payload),
        controller: payload[:params]['controller'],
        action: payload[:params]['action']
      }
    end
```

Is there any concern not to read from `payload[:controller]` and `payload[:action]`?

In Rails, I see the instrument payload contains the data in `payload`: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/instrumentation.rb#L18

**Comment by benlovell** [comment]
@zhuochun Thanks for pointing this out :heart_decoration:

**Comment by zhuochun** [comment]
Thanks for the fast response :+1:
