### ISSUE TITLE
Production environment log configuration example

### ISSUE THREAD

**Issue by Zyphrax** [roidrage/lograge#173]
This is not an issue, but I wanted to share with you guys a nice example of a log configuration for production (config/environments/production.rb).

  ```ruby
  config.log_level = :info
  config.log_tags = [:remote_ip]

  if defined?(Rails::Console)
    config.logger = Logger.new('/dev/null')
    config.after_initialize { ActiveRecord::Base.logger.level = 0 }
  else
    config.log_formatter = Logger::Formatter.new
    config.lograge.enabled = true
    config.lograge.custom_options = lambda do |event|
      { params: event.payload[:params].except('controller', 'action', 'format', 'status') } if event.payload[:exception]
    end
  end
```

Step-by-step:
- I set the log level to :info, I feel that the default :verbose logs far too much information for production
- I instruct Rails to add the remote IP of the request as a log tag. You can add :uuid here to help you recognize unique requests (I choose not to include it to reduce the log line length)

Then in case of console:
- When I use the Rails console on production, I don't want my actions to be logged to the production log file. In console mode logs will always appear in stdout. This is also a great way to prevent your work in console to accidentally mess up the ownership of the production log file.
- I increase the ActiveRecord log level because I like to see the queries behind the commands that I execute. This also makes it easier to track queries executed by after_commit, after_save etc.

And in case of normal requests:
- Resetting the log formatter will add a timestamp, log level etc. to the log messages
- I enable LogRage
- I ask LogRage to log the params (querystring, form data) only when an exception occurred. I remove a few parameters that are already in the log line (notice the shorter notation than in the README). And in case you wonder if Rails parameter filtering is applied to the params: YES!

**Comment by benlovell** [comment]
@Zyphrax Thanks! Looks like some sensible defaults here. Would you be willing to write up a page in the wiki?

**Comment by Zyphrax** [comment]
Hi @benlovell sorry for not replying to this, it totally slipped my mind.
I am quite busy at the moment, I hope to have time to set up a page in a few weeks.

**Comment by glaszig** [comment]
i'm also suffering this. i even followed [instructions in a book](https://books.google.de/books?id=w5QfDAAAQBAJ&lpg=PA480&dq=lograge%20logstash&pg=PA482#v=onepage&q&f=false).
it describes how to use lograge and logstash-logger to send logs off to logstash but logs are only being sent to logstash when restarting the server (apache + passener).
this looks to me like some sort of buffering issue -- any idea?

```rb
Rails.application.configure do
  config.lograge.enabled = true
  config.lograge.custom_options = lambda do |event|
    exceptions = %w(controller action format id)
    {
      params:      event.payload[:params].except(*exceptions).to_json,
      type:        :rails,
      environment: Rails.env
    }
  end
  config.lograge.formatter = Lograge::Formatters::Logstash.new
  config.lograge.logger    = LogStashLogger.new uri: 'udp://logstash-server:1234'
end
```
