### ISSUE TITLE
Suppress Stack Traces

### ISSUE THREAD

**Issue by sallustfire** [roidrage/lograge#177]
Hi,

For several production web apps I have, we're cleaning up the logs.  Lograge has been helpful in that.  However, stack traces are still being dumped.  We have gems like Honeybadger to handle exception reporting, so the stack trace just clutters the logs especially since the error message is included in the lograge output.

After doing a little searching, I couldn't find an obvious way via rails configuration to turn off the stack trace logging.  Even removing the action_dispatch.logger doesn't work, because it fails over to stderror.  The best I could come up with was to monkey patch ActionDispatch::DebugExceptions to disable the stack traces.

Is there a better approach?  Thanks.

**Comment by benlovell** [comment]
@sallustfire Sadly not at this juncture. This is something I'm looking into at the moment, but will require some rework to achieve. I'm going to try and document an approach that works as-is for now, so hopefully I'll have something up over the next few days.

**Comment by sallustfire** [comment]
I appreciate it.  I'm happy to provide a pull request if we can articulate a viable long term solution.

**Comment by bhushan-ahire** [comment]
Any update on this or found a better solution?
