### ISSUE TITLE
Questions on custom formatter! 

### ISSUE THREAD

**Issue by nguyenmv2** [roidrage/lograge#178]
This is more asking for help than an issue ( directly related to #31). 
Could someone show me how I should go about setting up a custom formatter ? I could not really understand the readme. Do I overwrite/extend the formatter I'm using ? or I have to write my own ? 

Thank you

**Comment by benlovell** [comment]
Hey @nguyenmv2 is this still something you'd like help with?

**Comment by nguyenmv2** [comment]
Yes, sir. My own research did not give me much information.

**Comment by benlovell** [comment]
It's quite simple when you know how. The formatter needs to be something `call`able so either a class that responds to `call` with one argument or a block with an arity of 1. Let's say you have a formatter class to format your log output something like `controller is: UserController, action is: create`:

```ruby
# custom_formatter.rb
class CustomFormatter
  def call(data)
    "controller is: #{data[:controller]}, action is: #{data[:action]}"
  end
end
```

The `data` is the hash of params / fields passed by Rails instrumentation.

And you configure it thus:

```ruby
# config/environments/production.rb
Rails.application.configure do
  config.lograge.formatter = CustomFormatter.new
end
```

Does that help?

**Comment by nguyenmv2** [comment]
Thank you for your help, @benlovell. Everything makes sense now
