### ISSUE TITLE
lograge does not install alongside rails5 rc2

### ISSUE THREAD

**Issue by radiospiel** [roidrage/lograge#179]
..since 

    lograge (= 0.4.0.rc1) was resolved to 0.4.0.rc1, which depends on railties (<= 5.0.0.rc1, >= 4)

I guess changing the dependencies from "<= 5.0.0.rc1" to "< 5.1" would resolve that issue satisfactorily.

**Comment by benlovell** [comment]
@radiospiel Give me a few moments and I'll have a compatible release. 👍
