### ISSUE TITLE
Custom fields not being logged when Rails controller raises exception

### ISSUE THREAD

**Issue by jackrg** [roidrage/lograge#180]
I have configured custom log fields as follows:

```
  config.lograge.custom_options = lambda do |event|
    user = User.find_by_auth_token!(event.payload[:cookies]['auth_token']) unless event.payload[:cookies].try(:[], 'auth_token').blank?
    params = event.payload[:params].reject do |k|
      ['controller', 'action'].include? k
    end
    { "params" => params, 'user_id' => user.try(:id), 'request_id' => event.payload[:uuid], 'ip' => event.payload[:ip] }
  end

```
Most of the time, the custom fields are logged just fine.

```
» 27 Jun 2016 16:20:11.242 351 <190>1 2016-06-27T23:20:10.958993+00:00 app web.1 - - [70284120350340] method=GET path=/images/book_covers/38290 format=html controller=book_covers action=show status=304 duration=45.60 view=0.00 db=32.23 params={"book_id"=>"38290"} user_id=2131 request_id=bbe0aea0-566f-4456-8c88-20026c8f506b ip=67.170.171.187
```

But, when the controller throws an exception, all of the custom fields are blank.

`» 28 Jun 2016 14:21:03.662 826 <190>1 2016-06-28T21:21:03.362381+00:00 app web.1 - - [70120415641220] method=POST path=/users/251 format=html controller=users action=update status=500 error='ActionView::Template::Error: undefined method '>' for nil:NilClass' duration=184.65 params={"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"XiB/p2e2vW3rhbxhlSyAkAn/tKJJSqJfhTMLfwDuAWw=", "user"=>{"email"=>"janelledenison@sbcglobal.net", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "full_name"=>"Janelle Denison", "friendly_name"=>"Janelle", "currency"=>"USD", "time_zone"=>"Pacific Time (US & Canada)", "daily_email"=>"10", "extra_emails"=>"", "my_referral_code"=>"G251", "my_referral_link"=>"https://www.booktrakr.com/?rcode=G251"}, "commit"=>"Save Changes", "id"=>"251"} user_id= request_id= ip=`

Exceptions are being handled by the default exception handler for Rails. I'm using Unicorn 4.6.2 with Ruby 2.0.0 and Rails 3.2.21. Lograge is 0.3.4.

**Comment by benlovell** [comment]
I couldn't replicate this in Rails 4 and above. We ended support for Rails 3.2 after v0.3.6, unfortunately. You may have some luck bumping your lograge version to 0.3.6 so I'd try there first.
