### ISSUE TITLE
ignore_actions issue after upgrading to 0.4

### ISSUE THREAD

**Issue by ZombieHarvester** [roidrage/lograge#185]
Rails 4.2.7, Ruby 2.2.5

i'm using [health_check](https://github.com/ianheggie/health_check) gem for app health monitoring. In my Lograge settings i have `config.lograge.ignore_actions = ['health_check/health_check#index']` to filter out heartbeats. 

Worked like a charm on `0.3.6`, after upgrading to `0.4.1` requests to `/health_check' no longer ignored. 

Would appreciate an advice.

**Comment by benlovell** [comment]
It's likely due to the changes in how the controller / action are specified. See #184. If changes of that nature solve the problem (or indeed if it persists) do let us know!

**Comment by ZombieHarvester** [comment]
using `HealthCheck::HealthCheckController#index` instead of  `health_check/health_check#index` solved the issue

thanks @benlovell 

ps. Wish it was in the Upgrade to 0.4 guide in the readme. It wasn't clear from the Changelog until you pointed to the corresponding commit

**Comment by benlovell** [comment]
@ZombieHarvester Apologies for that although to be fair it was a change in Rails, not our library. But still we didn't do a great job of documenting this - I'll add some upgrade docs. 👍
