### ISSUE TITLE
Rails5 support

### ISSUE THREAD

**Issue by USvER** [roidrage/lograge#188]
With Rails 5.0.0 i have default multiline logging.

**Comment by benlovell** [comment]
Could you be more precise?

**Comment by USvER** [comment]
When i install this gem my rails application still have dafault logging. What exactly should i clarify?

**Comment by benlovell** [comment]
Can I see how you've configured lograge, any other logging configuration and your lock file so I can understand your dependencies?

**Comment by USvER** [comment]
Added `gem "lograge"` to Gemfile
Added `config.lograge.enabled = true` to config/application.rb
Lockfile: https://gist.github.com/USvER/7b4f5475425f571851e8f5c2ebb6e523

**Comment by benlovell** [comment]
Nothing strikes me as obvious here - given what you've provided so far. Are any log lines being output in the single-line format from lograge? Or is lograge being entirely circumvented?

Do you have any other logging configuration happening in initializers or elsewhere in your stack that might be tampering with Rails' instrumentation?

**Comment by USvER** [comment]
No sign of lograge, just regular rails output.
I didn't played with logging anywhere.

**Comment by benlovell** [comment]
Could you provide a reproduction that I can play with?

**Comment by USvER** [comment]
Can't reproduce this with new clean rails app...
This should be something with my installed gems.
It's hard for me to localize the problem so i guess i will leave this as is. Sorry.

**Comment by benlovell** [comment]
No worries. Sorry I couldn't be of any more assistance.
