### ISSUE TITLE
Does append_info_to_payload actually do anything?

### ISSUE THREAD

**Issue by vincentwoo** [roidrage/lograge#191]
I can't get it to work with even something simple like

```ruby
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    payload[:wtf] = 'wtf'
  end
end
```

And when I [search for it in the code](https://github.com/roidrage/lograge/search?utf8=%E2%9C%93&q=append_info_to_payload), I don't find anything. Is this a deprecated thing leftover in the README?

**Comment by nguyenmv2** [comment]
you have to call super, and  append_info_to_payload is a Rails method.

**Comment by vincentwoo** [comment]
I was calling super, I just typed up the example too quickly, sorry.

I think the missing piece was I have to ALSO add a thing to custom_options in lograge.

**Comment by kgf** [comment]
@vincentwoo Could you please include what the thing you had to add to custom_options was ?

**Comment by vincentwoo** [comment]
You have to write a lambda that references the payload:

```ruby
  config.lograge.custom_options = lambda do |event|
    options = {
      params: event.payload[:params].reject { |k|
        ['controller', 'action'].include? k
      },
      ip: event.payload[:ip]
    }

    options[:user] = event.payload[:user] if event.payload[:user]
    options
  end
```
