### ISSUE TITLE
Logstash formatter seems to serialize for no need

### ISSUE THREAD

**Issue by gonzalocasas** [roidrage/lograge#192]
I might be wrong here, but I believe the logstash formatter is doing an extra `.to_json` serialization for no reason. Here's the current code:

```
      def call(data)
        load_dependencies
        event = LogStash::Event.new(data)

        event['message'] = "[#{data[:status]}] #{data[:method]} #{data[:path]} (#{data[:controller]}##{data[:action]})"
        event.to_json
      end
```

On [line 9](https://github.com/roidrage/lograge/blob/master/lib/lograge/formatters/logstash.rb#L9) there's a `.to_json`, but in fact, the class is already a `LogStash::Event` which logstash obviously handles. So, the serializations seems to be a loss of performance for no reason.

I tried locally to remove the `.to_json` and I don't see anything immediately broken, but I am not sure if there's additional dependencies to this that are not clear to me.

Tested with:
- lograge (0.4.1)
- rails (4.2.6)
- ruby 2.2.0
- mac OS X 10.10.5

**Comment by benlovell** [comment]
Interesting. I'm looking into this now. Thanks for reporting!

**Comment by benlovell** [comment]
It appears the call to `to_json` is explicitly required. Logstash does no post-processing of the event, rather the serialised JSON is read from the log - in most cases just `STDOUT` without prior knowledge of special handling for Logstash.
