### ISSUE TITLE
Add tenant to lograge content

### ISSUE THREAD

**Issue by BenJaziaSadok** [roidrage/lograge#193]
I really appreciate you work.
I have a multi-tenant rails app, i'm looking for a way to gather the current subdomain, so that i can analyse that with logstash.
Do you think it's possible to do get the tenant in addition to the info returned by lograge?

**Comment by benlovell** [comment]
Hey, thanks. 👌

This is definitely possible. You can either tag your logs (check the rails documentation for log tagging) or keep it purely lograge by following the README, specifically the section *You can also add a hook for own custom data*. Don't forget to also follow the section below that regarding `append_info_to_payload`. 

Let me know how it goes.

**Comment by BenJaziaSadok** [comment]
I worked like a charm, thank you.
I followed the readme, by adding a custom option with event.payload and add that to the custom_options in the logs.
I have another simple question, not sure if i should post it here:
Can you explain by details, what you mean by duration, view and db.
Last thing, i set active_record logger to nil, so the db value become always null, i think there is an improvement to do, since i don't need query details, only it's duration.

**Comment by benlovell** [comment]
Duration is total runtime, broken down into rendering time for the view(s) and querying time for the database. It's likely no issue for you just to ignore it in your logs, but if you want it removed you can add an exception for the `db` parameter in the payload.

Take a look at the code block here for some pointers: https://github.com/roidrage/lograge#what-it-doesnt-do

**Comment by BenJaziaSadok** [comment]
thank you @benlovell 
I will post a tutorial about this in few days here
[ELK-rails](https://github.com/BENZ-SYSTEMS/ELK-rails-monitoring)
