### ISSUE TITLE
The exception stack trace doesn't keep in the original Rails logger.

### ISSUE THREAD

**Issue by FX-HAO** [roidrage/lograge#196]
I have added ```config.lograge.keep_original_rails_log = true```, when an error occurs, I hadn't find any valuable infomation. It was just ```Completed 500 Internal Server Error in 40ms (ActiveRecord: 6.1ms)```, absolutely i want more information about the exception, it should be something more like the following:

	Completed 500 Internal Server Error in 1899ms (ActiveRecord: 92.4ms)

	GRPC::BadStatus (14:{"created":"@1480919280.562705000","description":"OS Error","errno":54,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}):
	  app/service/chauffeur_service.rb:14:in `dispatch_passenger_order'
	  app/models/passenger_order.rb:37:in `dispatch_passenger_order'
	  app/controllers/spree/api/v1/passenger_orders_controller.rb:25:in `create'

**Comment by benlovell** [comment]
[Take a look here](https://github.com/roidrage/lograge#logging-errors--exceptions).

**Comment by FX-HAO** [comment]
@benlovell Thanks for your quick response, but your answer is not what i want, i'm wondering that is there a way to keep stack trace in original Rails logger, NOT logstash.

**Comment by benlovell** [comment]
@FX-HAO At which loglevel have you configured your logs?

**Comment by FX-HAO** [comment]
@benlovell debug

**Comment by FX-HAO** [comment]
Sorry, it's my bad. Because a line of ```config.action_dispatch.show_exceptions = false```.

**Comment by benlovell** [comment]
@FX-HAO Ah, no problem. 👍
