### ISSUE TITLE
Thread.current[:lograge_location] leaks into other requests

### ISSUE THREAD

**Issue by leonelgalan** [roidrage/lograge#197]
Lograge version: 0.4.1
Rails version: 4.2.7.1
Ruby Version: 2.2.5

Last week I enforced (by redirecting) a new subdomain on a large set requests on my app. These, individually logged right, as volume increased I started noticing requests outside of this set to be logged as redirects, but with the right status codes (201, 200, etc)

I've come to the conclusion that this requests were fulfilled by threads that had stored: `Thread.current[:lograge_location]`

I'm happy to take a deeper look into it, and work on a solution. But I wanted some sort of confirmation that I'm on the right path and discuss possible solutions before working on one. 

I used my own formatter, but this should give you an idea of what I'm describing:

```
Jan 22 17:20:16 heroku-app-1234 app/web.5:  174.193.160.113    GET 200 /api/resource redirect_to=http://new_subdomain.example.com/other_resource (app:168.58ms db:37.26ms)
Jan 22 17:20:33 heroku-app-1234 app/web.8:  114.143.77.146     GET 302 /other_resource redirect_to=http://new_subdomain.example.com/other_resource (app:0.0ms db:6.41ms)
```

API requests don't redirect. In this case the app got the data and status code right, but it was logged with a "redirect_to". The second line correctly logged the redirected to the same resource on the "new_subdomain".

**Comment by benlovell** [comment]
That sounds entirely possible. Some app servers won't clear thread locals (per request for example) without explicit opt-in. I know for sure puma has a `clean_thread_locals` option that controls this behaviour. Depending on your application server this may be a smart place to start.

Please do feedback anything you find.

**Comment by abrisse** [comment]
You could use [request_store](https://github.com/steveklabnik/request_store) gem instead of using Thread.current

**Comment by benlovell** [comment]
@leonelgalan Did this problem persist? Switching out to `request_store` seems reasonable to me. Is that something you're interested in tackling?

**Comment by leonelgalan** [comment]
Let's do this! PR soon!
