### ISSUE TITLE
db value is null when active_record.logger is null

### ISSUE THREAD

**Issue by BenJaziaSadok** [roidrage/lograge#200]
Hello,
lograge works perfectly for me exept one thing,
I have to remove active record log to be able to filter the logs.
It returns a value when active records logs are active, but in my case i have remove the query logs.
So when i do that with config.active_record.logger = nil, the db duration value returns 0.
Are there a manner to deal with that ?

**Comment by benlovell** [comment]
Is it related to this: rails/rails#24963 ?

**Comment by BenJaziaSadok** [comment]
Yes exactly, as i saw, it will be fixed in rails 5.0.2 and above.
Thank you
