### ISSUE TITLE
Rails 5.1 support

### ISSUE THREAD

**Issue by bobbytables** [roidrage/lograge#204]
Currently the gemspec is set to `< 5.1` preventing usage with Rails 5.1 Any plans to update or has this been tested with Rails 5.1?

**Comment by benlovell** [comment]
It's fairly trivial if you wanted to contribute and are comfortable doing so. From what I can see it's just a case of loosening that dependency. No breaking changes.

Otherwise I'll get this turned around tomorrow and cut a pre release.

**Comment by bobbytables** [comment]
I should have been more specific in asking if there were known breaking changes. I can make the change real quick.
