### ISSUE TITLE
Parse log from Grape-API

### ISSUE THREAD

**Issue by BenJaziaSadok** [roidrage/lograge#216]
Hi, i would like to add customized format to logs related to API calls using grape API.
And in a second step, make the logs from the app and from the api unifom, so that it would be easy to index and search on them.
There are many manners to activate logs on grape, but none are related to specific format.
It would be perfect to add a lograge plugin to parse them.
I you can provide a guidance, i will help on the development

**Comment by benlovell** [comment]
Grape isn't something I use myself, so I'm not sure how much help I'd be on that front, but happy to help out where possible if you want to take the lead on the development of a grape-compatible plugin. I seem to remember a grape middleware that does something similar for lograge so maybe worth checking that out first.

Ping me once you're started and if you need any help!

**Comment by ryan-raimer** [comment]
In case someone comes by this at some point (say 3 year later), you can use the [grape_logging gem](https://github.com/aserafin/grape_logging) and configure the logs to be sent to the default rails logger where lograge can then pick them up. 

Not saying it's the best way to do it, but if you need to.
