### ISSUE TITLE
Cannot change log destination

### ISSUE THREAD

**Issue by sasasasumna** [roidrage/lograge#220]
Hi
I'm probably doing something wrong, but I can't seem to change the log destination. Ideally I would write to STDOUT, but I'll settle for writing to `/var/log/#{app_name}` after setting up `logrotate`. Everything else seems to work with lograge, except that my logs are always getting written to the default location of `log/#{Rails.env}.log`.

Here's my config
```ruby
include_in_log_message = {
  env: Rails.env,
  host: ENV.fetch('HOST') { 'localhost' }
}
ignore = %w(controller action)

Rails.application.config.log_level = ENV.fetch('LOG_LEVEL') { 'debug' }.upcase
Rails.application.config.log_tags = [:remote_ip]

if defined?(Rails::Console)
  Rails.application.config.logger = Logger.new('/dev/null')
  Rails.application.config.after_initialize { ActiveRecord::Base.logger.level = 0 }
else
  Rails.application.config.lograge.formatter = Lograge::Formatters::KeyValue.new

  Rails.application.config.lograge.custom_options = lambda do |event|
    data = event.payload
    addons = {}
    if data[:exception].present? && (Rails.env.development? || Rails.env.test? || Rails.env.staging?)
      addons[:error] = { type: data[:exception], content: data[:exception_object]}
    end
    addons[:params] = data[:params].except(*ignore) if data[:params].present?

    include_in_log_message.merge(addons)
  end
  Rails.application.config.lograge.enabled = true
end
```

This is the case on both Mac OS X 10.12 and on Ubuntu 16.04. I'm on Ruby 2.4.1, Rails 5.1.3, and lograge 0.6.0. The issue persists no matter how I start the app, whether it's with `bundle exec puma -C config/puma.rb`, `foreman start`, or just `rails s`. In production I use `foreman export` to create a `systemd` service.

Thank you!

**Comment by benlovell** [comment]
Most folks just symlink that directory when logging to disk in production-like environments.

However, you can configure the log location with Rails per the following:

```ruby
# production.rb
Rails.application.configure do
  # ...
  logger = ActiveSupport::Logger.new('/var/log/whatever.log')
  config.logger = ActiveSupport::TaggedLogging.new(logger)
end
```

**Comment by sasasasumna** [comment]
Thanks @benlovell 

With your suggestion, I can now log to `STDOUT` when starting with `rails s`. The next issue now is that `puma` swallows `STDOUT`, which of course means `foreman` cannot report logged events to `STDOUT` either. Time to dig some more.
