### ISSUE TITLE
Not filtering query string params

### ISSUE THREAD

**Issue by bluengreen** [roidrage/lograge#229]
I'm seeing sensitive data logged (api keys, etc) that is coming from the querystring. The path isn't being filtered for the query string. Any suggestions on how to do that other than remove the action / controller from being logged?

**Comment by benlovell** [comment]
When you append the params to your payload make sure you do it with your request’s `filtered_parameters`. Otherwise you’re including params pre the filtering.

**Comment by bluengreen** [comment]
Hmm. I'm not changing the payload. And only the query string params are the issue. All others are filtered.

**Comment by benlovell** [comment]
OK, they're being included in the path? The easiest thing to do is to exclude that action as you rightly stated. Otherwise, I'd happily accept a patch that performs the requisite filtering at `Lograge::RequestLogSubscriber#extract_path`.
