### ISSUE TITLE
Configuring LogRage

### ISSUE THREAD

**Issue by gogocurtis** [roidrage/lograge#245]
Hi - I'm wondering if there is a way to configure LogRage to let me know when a Request is started?

I see the status= for the request After everything is happening - I can force the server to process a single request at a time, but i'm not sure how to make LogRage tell me when a request is starting instead of when it is over - Something important for when debugging complex concurrency issues.

My work around is to disable it - but it does help with clearing out the view render data so i'd thought I would ask.

best,
Curtis

**Comment by benlovell** [comment]
The short answer is no. Interleaving log lines are something we specifically set out to avoid.

Good luck debugging your concurrency issue!
