### ISSUE TITLE
custom_options event.time changed from rails 5.2.2 

### ISSUE THREAD

**Issue by jlemaes** [roidrage/lograge#266]
In the readme there is a section to add the time to the logs:
```
 config.lograge.custom_options = lambda do |event|
    { time: event.time }
 end
```

This isn't the correct time anymore since this rails commit: https://github.com/rails/rails/commit/7c4542146f0dde962205e5a90839349631ae60fb (included from Rails 5.2.2), because now `Process.clock_gettime(Process::CLOCK_MONOTONIC)` is used as start time for events, which is the monotonic time since boot. 

Can this be replaced in the readme with ` { time: Time.now }`?

**Comment by pxlpnk** [comment]
@jlemaes Sounds good, could you please propose a PR?

**Comment by jlemaes** [comment]
@pxlpnk See #267

**Comment by pxlpnk** [comment]
Super thanks! 👍

**Comment by FeminismIsAwesome** [comment]
Hi @jlemaes, just wondering--does that change how precise the timing of said event is? I worry by doing that, if the request took a while to load that we lose the actual time the event came through. But perhaps that is wrong?

**Comment by zachwalton** [comment]
+1 to @FeminismIsAwesome's question. I think instead you want:

```
now = Process.clock_gettime(Process::CLOCK_MONOTONIC)

start_time = (now - event.time).seconds.ago
end_time = (now - event.end).seconds.ago

config.lograge.custom_options = lambda do |event|
   { start_time: start_time, end_time: end_time }
end
```

**Comment by aguynamedben** [comment]
This happened in my Rails app, using lograge and the Datadog Heroku buildpack.

I found the fix by following what GitLab did: https://gitlab.com/gitlab-org/gitlab-foss/-/commit/aeb67dd489b1ccc7f0ab1d702725729ab9cc3e27#7fbfd491b0620e7fa9f3cd8818582f52ce3e8f31_22_21

Thanks for updating the README!

**Comment by AlexWayfer** [comment]
The bad thing with `config.lograge.custom_options` is that it doesn't applies to simple additional logging like this:

```ruby
Rails.logger.info(
  # ...
)
```
