### ISSUE TITLE
Better way to handle invalid charecter encoding in request params?

### ISSUE THREAD

**Issue by wjessop** [roidrage/lograge#277]
I've hit an issue with lograge. We are getting invalid characters in some of our POST params. We handle this fine in the controller, but when the controller finishes lograge tries to log the request as JSON and this (understandably) errors:

    Could not log "process_action.action_controller" event. JSON::GeneratorError: source sequence is illegal/malformed utf-8 ["backrtrace", "lines"]

You can trigger this using something like the following curl command:

```
curl -v --request POST \
  --header 'Content-Type: multipart/form-data; boundary=xYzZY' \
  --form "email=`ruby -e 'puts "\255"'` " \
  'https://somehost/webhooks/inbound_emails/process_email'
```

I still want to log the data, but with the invalid chars stripped. The only way I can see to solve this is to create my own log formatter:

```ruby
module Lograge
  module Formatters
    class JsonNoError
      def call(data)
        ::JSON.dump(data)
      rescue JSON::GeneratorError => e
        if data[:controller] == 'Webhooks::InboundEmailsController' && data[:action] == 'process_email'
          data[:params]['email'] = strip_naughty_bytes(data[:params]['email'])
          ::JSON.dump(data)
        else
          raise e
        end
      end
    end
  end
end
```

Then configure this in application.rb:

```ruby
config.lograge.formatter = Lograge::Formatters::JsonNoError.new
```

This is pretty nasty though. It dislocates the logic of fixing up the data from the controller/action (app/controllers, lib/somedir), and means we have to hard code the controller/action name, and also include logic for *not* fiddling with the data when it's not the controller we want to fix up.

I had in mind (and was looking for, but may have missed) something like this:

```ruby
class Webhooks::InboundEmailsController < ActionController::Base
  before_logging :strip_invalid_bytes, only: [ :process_email ]

  def process_email
    # things
  end
end
```

Is there a better way to do this?

**Comment by josefbilendo** [comment]
As mentioned in the docs, lograge offers a hook (`append_info_to_payload`) to add additional information to the logs:
```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
  end
end
```

As an alternative to your custom formatter you can modify the params with invalid encoding directly in your controller:
```ruby
class Webhooks::InboundEmailsController < ActionController::Base
  def process_email
    # things
  end

  private

  def append_info_to_payload(payload)
    super
    payload[:params]['email'] = strip_naughty_bytes(params['email'])
  end
end
```

**Comment by wjessop** [comment]
For what it's worth I don't think that this was about appending extra data to the logs, but was about lograge attempting to log by default something it wasn't able to. I can't check though because I stopped working at the company that had the issue last year!
