### ISSUE TITLE
Passwords show in Rails logs when lograge is enabled and custom options are provided

### ISSUE THREAD

**Issue by ghiculescu** [roidrage/lograge#28]
When using standard Rails logging, fields named password are filtered out before being logged. So they show up as `:password=>\"[FILTERED]\"`

When using lograge, this filtering doesn't happen - the param shows up as `"password"=>"hunter2"` in the logs.

Note: this doesn't happen by default, it only happens if you are passing parameters through using `append_info_to_payload`.

**Comment by fabioperrella** [comment]
Hi, I have the same problem using rails 4.2.3 and lograge 0.9.0

What about reopen this issue?
