### ISSUE TITLE
lograge not showing messages

### ISSUE THREAD

**Issue by steveburkett** [roidrage/lograge#298]
Hi there, 

noob issue i'm sure, but i havent been able to determine what's going on. Cant get this to work, any tips appreciated. 

I enable lograge in development.rb

```
  config.log_level = :debug
  config.lograge.enabled = true
  config.lograge.logger = ActiveSupport::Logger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"
  config.lograge.custom_options = lambda do |event|
    {
      time: Time.now.utc,
    }
  end
```

Then, i do a test in a rails console: 

```
[3] pry(main)> Rails.logger.info('testing')
=> true
```

Nothing in the log file 
```
[ruby-2.5.0](git:sb/309-clean-up-logs):log $ cat lograge_development.log 
# Logfile created on 2019-08-05 13:10:02 -0700 by logger.rb/61378
[ruby-2.5.0](git:sb/309-clean-up-logs):log $ 
```

but simple format message in development.log
```
[ruby-2.5.0](git:sb/309-clean-up-logs):log $ cat development.log 
testing
```

If i try this thru a `rails s`, slightly different results but not quite right:

```
[ruby-2.5.0](git:sb/309-clean-up-logs):log $ cat development.log 
[127.0.0.1] test1
[127.0.0.1] test2
```

for 
```
    Rails.logger.info('test1')
    Rails.logger.info('test2')
```
 
in a controller method, with this configuration
```
  config.lograge.enabled = true
  config.log_tags = [ :remote_ip ]
  config.lograge.base_controller_class = 'ActionController::API'
  # config.lograge.logger = ActiveSupport::Logger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"
  config.lograge.custom_options = lambda do |event|
    {
      time: Time.now.utc
    }
  end
```

**Comment by teekenl** [comment]
@steveburkett  I see this issue has been closed now. Did you figure the solution for this? I got into same problem.

**Comment by taman9333** [comment]
@teekenl have you figure out any solution for this

**Comment by Kotnstantin** [comment]
> @steveburkett I see this issue has been closed now. Did you figure the solution for this? I got into same problem.
Now I’m in the same trap, you solved the question?

**Comment by lednerb1** [comment]
Same problem
