### ISSUE TITLE
Issue with AnyCable: undefined method `protocol' for nil:NilClass

### ISSUE THREAD

**Issue by wongy91** [roidrage/lograge#304]
https://github.com/roidrage/lograge/blob/2347f635f0cd3d8c21f0159e797ed341f63a925d/lib/lograge/rails_ext/action_cable/connection/base.rb#L8

where is the `websocket` object initialized?

Application error: undefined method `protocol' for nil:NilClass
Application error: undefined method `protocol' for nil:NilClass

**Comment by jpalumickas** [comment]
We have the same problem

**Comment by danielnc** [comment]
we have same problem

**Comment by uhrohraggy** [comment]
FYI This is still an open issue. https://github.com/anycable/anycable-rails/issues/103 has more details on why this PR exists, and is desperately needed. Please review
