### ISSUE TITLE
Support for custom formatters

### ISSUE THREAD

**Issue by fguillen** [roidrage/lograge#31]
I can easily add `custom_options` but not removing default options, or changing the order.

Now you can choose among 3 formatters:
- lograge
- logstash
- graylog2

But you can't create your totally custom formatter. I'm missing the possibility to assign a block to the `log_format` configuration option like:

```
config.lograge.log_format = lambda do |event, data| { "my custom log: #{data[:path]}" }
```

**Comment by marlonwc3** [comment]
It's already possible to change the output order?

**Comment by benlovell** [comment]
@marlonwc3 You could do that with a custom formatter. Either by creating a custom formatter class or by providing a `call`able object, generally a block:

```ruby
# config/environments/production.rb
MyApp::Application.configure do
  config.lograge.formatter = ->(data) { "Called #{data[:controller]}" } # data is a ruby hash
end
```
