### ISSUE TITLE
Request: new gem release

### ISSUE THREAD

**Issue by swrobel** [roidrage/lograge#364]
It isn't mentioned in the Unreleased section of the Changelog, but support for [Rails allocations](https://github.com/roidrage/lograge/pull/355) has been added, but not released to rubygems. A new release would be appreciated so we don't have to pull from github in our Gemfile!

**Comment by northeastprince** [comment]
@pxlpnk @ivy not sure who's maintaining this since the owner seems to be inactive

**Comment by pxlpnk** [comment]
@benlovell has the rights to publish a new release to rubygems.

**Comment by swrobel** [comment]
@benlovell I hate to be annoying, but a release would be greatly appreciated so we don't have to keep pulling the gem from git!

**Comment by benlovell** [comment]
@swrobel Hey, sorry for the wait. In progress now and should be released shortly.
