### ISSUE TITLE
Custom options not appearing for exception log lines

### ISSUE THREAD

**Issue by nicholasmott** [roidrage/lograge#37]
I believe that this is not a lograge issue but I'm not certain so I thought I'd raise it.

When an exception occurs, and a 500 is logged, custom options are missing from the log line.

For example:

If I have the following in `/config/environments/production.rb`
```
config.lograge.custom_options = lambda do |event|
  {
    remote_ip: event.payload[:remote_ip],
    request_id: event.payload[:request_id]
  }
end
```

I'm then appending to the payload in my `application_controller.rb`
```
def append_info_to_payload(payload)
  super
  payload[:remote_ip] = request.remote_ip
  payload[:request_id] = request.env['HTTP_HEROKU_REQUEST_ID']
end
```

I get the following for an exception log line.
```
method=POST path=/users.json format=json controller=users action=create status=500 error='NoMethodError:undefined method `id' for nil:NilClass' duration=447.09 remote_ip= request_id=
```

Both `remote_ip` and `request_id ` are blank.

Log lines for successful transactions are receiving the `remote_ip` and `request_id` correctly so I suspect the issue is that Rails is not passing the additional payload items when there is an exception.

Any ideas on how this info could be made to flow through?

**Comment by kommen** [comment]
FYI, this is now fixed in rails. https://github.com/rails/rails/pull/17978

**Comment by benlovell** [comment]
:heart:

**Comment by nicholasmott** [comment]
Awesome.
