### ISSUE TITLE
Inconsistent logs

### ISSUE THREAD

**Issue by thelinuxlich** [roidrage/lograge#72]
I'm receiving request logs correctly, but when Rails throws any error, the log goes to Kibana in 3 or more parts without a clean format.

**Comment by mpugach** [comment]
For now you can delete the middleware responsible for this and add the backtrace to the payload if you want.

```ruby
  config.middleware.delete ActionDispatch::DebugExceptions

  config.lograge.custom_options = lambda do |event|
    payload = { params: event.payload[:params].except('controller', 'action', 'format') }

    exception_object = event.payload[:exception_object]

    payload.merge!({ backtrace: exception_object.backtrace.join("\n") }) unless exception_object.blank?

    payload
  end
```

**Comment by collimarco** [comment]
+1 I use lograge with logstash-event to send events to ELK and I have the same issue: each line of the backtrace is sent separately and thus is displayed in random order, making it useless.

I think that this gem is the appropriate place to fix this logging behavior and would be great to see that fix enabled by default:

> Lograge is an attempt to bring sanity to Rails' noisy and unusable, unparsable and, in the context of running multiple processes and servers, unreadable default logging output.

**Comment by mpugach** [comment]
@collimarco here is a good start [Submitting A Pull Request](https://github.com/roidrage/lograge/blob/master/CONTRIBUTING.md#submitting-a-pull-request) 😉

**Comment by collimarco** [comment]
@mpugach You can do the same ;) I did not ask anyone to fix this... Sorry if my message was misunderstood: the meaning is that, from a technical point of view (**modularity**), this feature pertains to the scope of this gem.

@thelinuxlich Can you please keep this issue open? I think that it's a common case and many people faces this issue... It would be useful to keep it open for reference until this behavior is fixed or at least it is better documented
