### ISSUE TITLE
Each log line is prefixed with I, TIMESTAMP  INFO --

### ISSUE THREAD

**Issue by rahilsondhi** [roidrage/lograge#84]
Lograge was working fine with the logstash format, but now all of a sudden each log line is prefixed with a timestamp and `INFO --`, like this:

`I, [2014-09-19T00:44:13.799675 #18431]  INFO -- [JSON]`

Before, each line was just a JSON logstash-event hash.

This problem occurs in our rails 4.1.5 app, but not in our rails 3.1.12 app.

This problem **occurs in production, but not in development**.

The rails 4 app is using lograge 0.3.0 and logstash-event 1.2.02.

Any ideas how this could have happened or how we can solve this?

**Comment by leonelgalan** [comment]
I didn't have that line (updated from older Rails) and still see this issue. I'm using the default formatter (key-value)

**Comment by MatthiasWinkelmann** [comment]
I had the same problem. I solved it by replacing the line

> config.logger = ::Logger.new(STDOUT)

with

> config.logger = ActiveSupport::Logger.new(STDOUT)

**Comment by toebbel** [comment]
Solution of @rahilsondhi :-1:
Solution of @MatthiasWinkelmann :+1:

**Comment by sybind** [comment]
Commenting this line as @rahilsondhi worked for me.
```
  # Use default logging formatter so that PID and timestamp are not suppressed.
  config.log_formatter = ::Logger::Formatter.new
```

 However, I am still seeing "Cache digest ..." messages in my log file. Any ideas?
```
  Cache digest for /home/sybind/.rvm/gems/ruby-2.2.1@xxx/bundler/gems/spree_bootstrap_frontend-d20c03352917/spree_bootstrap/frontend/app/views/spree/shared/_products.html.erb: f154cddd92bc8447c885e71800fb5896
```

**Comment by Seitk** [comment]
@MatthiasWinkelmann's one works for me

**Comment by huguesbr** [comment]
solved it by logging to different file: `config.lograge.logger = ActiveSupport::Logger.new("#{Rails.root}/log/#{Rails.env}_lograge.log")`
