### ISSUE TITLE
Appending info to payload should happen in/around config, not in controller.

### ISSUE THREAD

**Issue by smudge** [roidrage/lograge#94]
Something about the way I have to append additional info to the payload (i.e. overriding `append_info_to_payload` inside of my `ApplicationController`) feels messy. It requires defining the same custom options in 2 different locations, very far apart. This is something I'd much prefer to do right next to where I configure lograge, or at least in an initializer, so that when I (or a team member) come back to this in 6 months it isn't totally confusing.

For now, I have an initializer (`lograge.rb`) set up that looks like this (>= ruby 2.0):

``` ruby
module LogrageControllerOverride
  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
    payload[:fwd] = request.remote_ip
    payload[:user_id] = current_user.try(:id)
  end
end

# should probably do this only if Rails.env is production
ActionController::Base.send :prepend, LogrageControllerOverride
```

And then in `config/environments/production.rb` I have this:

``` ruby
config.lograge.enabled = true
config.lograge.custom_options = lambda do |event|
  {
    time: event.time.to_i,
    host: event.payload[:host], # see: config/initializers/lograge.rb
    fwd: event.payload[:fwd].try(:inspect),
    user_id: event.payload[:user_id]
  }
end
```

But I'd still prefer to be able to do all of this from `config/environments/production.rb` along with the above config code. As in, specify a proc which will be called in the context of the controller, so I'd have direct access to the usual things like `request` and `current_user`. Does that make sense?

**Comment by pxlpnk** [comment]
@smudge did you have some time to play around with this?

**Comment by benlovell** [comment]
@smudge?

**Comment by smudge** [comment]
(Bueller...)
