### ISSUE TITLE
invalid timestamp format

### ISSUE THREAD

**Issue by andywenk** [roidrage/lograge#95]
I have the following log entry created by lograge
      
    {"method":"GET","path":"/warenkorb","format":"json","controller":"carts","action":"show","status":200,"duration":4.69,"view":0.3,"db":0.0,"name":"development","session":"a93fa3308f8873b179c091ad287534c8","host":"localhost","@timestamp":"2014/11/28 12:56:09 +0000","@version":"1","message":"[200] GET /warenkorb (carts#show)"}

The timestamp bit looks like this:

    "@timestamp":"2014/11/28 12:56:09 +0000"

Unfortunately, logstash is responding with this error:

    A plugin had an unrecoverable error. Will restart this plugin.
    Plugin: <LogStash::Inputs::Stdin >
    Error: Invalid format: "2014/11/25 13:14:30 +0000" is malformed at "/11/25 13:14:30 +0000" 
    {:level=>:error}

When changing the format by hand for test purposes to:

     2014-11-27T14:45:02.928Z

it is working. I am not sure where the error is. Is this a lograge, logstash or Rails config error?

Thanks for any help

**Comment by pxlpnk** [comment]
It seems this is fixed in the `1.2.x` version: https://github.com/elasticsearch/logstash/blob/v1.2.2/lib/logstash/event.rb

I don't see where lograge is enforcing any version of `logstash-event` except for the tests.

**Comment by pxlpnk** [comment]
@andywenk is the current master 940cba8dd98ee6efef9a55a3cd3b46af6465e341 working for you?

**Comment by andywenk** [comment]
it should look like this I think:

https://github.com/elasticsearch/logstash/blob/v1.2.2/lib/logstash/event.rb#L37

But what I have when using master from github is:

    {
       ... 
       "@timestamp": "2015/02/08 14:13:39 +0000",
       "@version": "1",
       "message": "[200] GET /warenkorb (carts#show)"
    }

The configuration from above is the same. Am I missing something? Am I the only one with this problem?
Thanks a lot for looking into this ;-)

**Comment by andywenk** [comment]
ok it is a bit clearer now. I created a new application and used the same settings and there it is working:

    {
        "@timestamp": "2015-02-08T14:45:26.847Z",
        "@version": "1",
        "message": "[200] GET / (start#index)"
    }

I think some other gem is doing bad things so that it does not work correctly. I will investigate this further and let you know. If it matters, you can close this issue.

Thanks for everything!

**Comment by pxlpnk** [comment]
As lograge doesn't do anything about the date format I suggest checking the gems then too.
I am closing this issue for now. But please feel free to report the result of your research in this ticket.

**Comment by andywenk** [comment]
@pxlpnk the problem is couch_potato which is monkey patching Date globally.

https://github.com/langalex/couch_potato/issues/105

I will close this now ;-)

**Comment by pxlpnk** [comment]
![](http://picardfacepalm.com/updown.gif)

Thank you for investigating this!

**Comment by andywenk** [comment]
you're welcome ;-)
